apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iz246xxzo-go 
  janus-idp.io/tekton: iz246xxzo-go
  backstage.io/kubernetes-id: iz246xxzo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iz246xxzo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml